#
#logging:
#  level:
#    com.well.image.consumer: INFO
#  pattern:
#    console: "%date{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %highlight(%-5level) %cyan(%logger{36})  - %msg%n"
#    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
#  file: logs/application.log

fdfs:
  connect-timeout: 2000
  so-timeout: 3000
  tracker-list:
    - 10.10.13.50:22122
server:
  port: 8080


image:
  host: xxxxx
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB